### ISSUE TITLE
[Feature] Enable macosXX-arm as a build target for macOS computers with new m1 silicon running the arm dotnet runtime

### ISSUE THREAD

**Issue by jaysonjphillips** [furesoft/Slithin#101]
Hi team! Here's the user statement:

## Problem
I loved that there's a build and release for macOS. However, when installing the native dotnet runtime for macOS arm64, Slithin won't run the macOS build unless I also install the x64 dotnet runtime (which would enable Slithin to run with Rosetta). I also wasn't about to build from source with the default runtime. 

## Solution
A clear solution to solve this would be to add `osx.12-arm64` as a runtime identifier. Then, one could generate a release using a modified build command `dotnet publish [path/to/Slithin.csproj] -c Release -r osx.12-arm64 -o [path/to/output]`

I haven't considered any alternatives, especially since I'm a user who has other `.NET` projects that require the arm64 version of the runtime and not the x64 version running in Rosetta. Happy to submit this small change as a PR

**Additional context**
Here's the generated output of my `dotnet` runtime install

```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.2
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Screenshot of the build working**
<img width="1682" alt="slithin-screenshot" src="https://user-images.githubusercontent.com/58239/160148548-e6765a40-fa8b-42ff-adb1-5f816b141abf.png">

**Comment by furesoft** [comment]
Feel free to make a Pull Request

**Comment by furesoft** [comment]
I added this to the build pipeline
