### ISSUE TITLE
[Bug] Crash when pressing connect with no info

### ISSUE THREAD

**Issue by ElDavoo** [furesoft/Slithin#230]
**Describe the bug**
When you press "connect" without saved devices or infos (ip address and password), the program will load for many seconds and then crash.

**To Reproduce**
1. Install app
2. Click connect

**Expected behavior**
I expected basic form validation (a message like "ip is empty, password is empty")

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 1.0.15.0

**Comment by furesoft** [comment]
What did you enter to login?

**Comment by ElDavoo** [comment]
nothing

**Comment by ElDavoo** [comment]
![image](https://user-images.githubusercontent.com/7345120/175048326-35d99407-031c-4f43-9827-b82773eb0087.png)
In Windows Sandbox, this appears on version 1.0.18.0 (minor layout problem)

**Comment by ElDavoo** [comment]
> hmm. I have tested it without an exception. Did you do anything special?

No, but the error is fixed (even though the text layout is wrong)
