### ISSUE TITLE
[Bug] new custom Templates have invalid icon

### ISSUE THREAD

**Issue by Snaid1** [furesoft/Slithin#231]
**Describe the bug**
When adding a new custom template, the icon is incorrectly assigned with the \ escaped in templates.json. causing the icon to 

**To Reproduce**
1. in Slithin
2. Go to Templates
3. Click on Add
4. select everything needed to add a template including an icon code.
5. click ok
6. on your remarkable
7. open or create a workbook
8. change template
9. see icon code instead of icon for template

**Expected behavior**
it displays the icon correctly

**Desktop (please complete the following information):**
 - OS: Windows 10
 - reMarkable 2
 - Version 2.12.3.606

**Additional context** 
issue is the icon code being added with \\ at the beginning instead of \. If I manually edit the templates.json file to remove the extra \ it works fine.

**Comment by furesoft** [comment]
I have fixed it. Thanks for your information. The fix will be available in the new version.
