### ISSUE TITLE
[Bug] Can't run in Windows Sandbox by double-click

### ISSUE THREAD

**Issue by ElDavoo** [furesoft/Slithin#236]
**Describe the bug**
When double-clicking on Slithin.exe in Windows Sandbox, a strange message appears and program does not start.
The program will boot fine if started from PowerShell.

**To Reproduce**
1. Open Windows Sandbox
2. Double click slithin.exe

**Expected behavior**
Program that starts

**Screenshots**
![image](https://user-images.githubusercontent.com/7345120/175048760-4152e680-9413-4fc0-a502-b739be9c54d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 (sandbox)
 - Version 1.0.18.0

**Additional context** 
idk

**Comment by furesoft** [comment]
Have you installed .Net 6?

**Comment by ElDavoo** [comment]
I tried installing the desktop runtime and it did not work

**Comment by furesoft** [comment]
It looks like the Windows Sandbox doesn't allow running .net applications
