### ISSUE TITLE
Can't run consistently

### ISSUE THREAD

**Issue by regrubtaf** [furesoft/Slithin#24]
Can't seem to get it to run consistently in Win 10 (x64). Sometimes it just closes after logging in.  One time, it started downloading files from the rM2 (2.8.0.98) and then restarted the rM2, then it closed the application, leaving a cmd window open.  Haven't gotten to do much testing in earnest.

**Comment by furesoft** [comment]
What did you do. Does this problem happen on initial download or when click Sync?

**Comment by regrubtaf** [comment]
I haven't had the opportunity to do much clicking.  All of the described occurred after launching and logging in.

**Comment by markussilvan** [comment]
I have the same issue with rM2 (2.7.2.56) in Win10 x64. Brand new rM2 and Slithin just installed. Happens everytime I start Slithin.

  1. In the connect dialog, I enter IP address and password. Click connect.
  2. Main window opens. I see it downloading `Windows_x64.zip`, and during the download everything seems to work just fine in the background. I can go to notebooks view and see notebooks from rM2 in the main window.
  3. Downloading `Windows_x64.zip` is completed. Command line window opens and main window closes.

**Comment by furesoft** [comment]
I have published a new version to the store. does it works now?

**Comment by markussilvan** [comment]
Yes, it works now.
