### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by P-C-R** [furesoft/Slithin#250]
How can i change the Screens? Whats the process to do so?

Best

**Comment by furesoft** [comment]
Hey,

you can simply drag your image over the screen you want to replace

**Comment by P-C-R** [comment]
Dont work here with the latest version. I am on Fedora 36. Tried Wayland and Xorg.

**Comment by furesoft** [comment]
Hmm. Maybe you don't have enough space on your device?

**Comment by P-C-R** [comment]
Nah. Both enough space



Chris ***@***.***> schrieb am So., 11. Sept. 2022, 20:42:

**Comment by furesoft** [comment]
have you installed custom templates?
