### ISSUE TITLE
Keeps trying to download a Win 64 zip file opens cmd and stops there. 

### ISSUE THREAD

**Issue by stburrus** [furesoft/Slithin#30]
**Describe the bug**
Upon opening and connecting to Slithin it will attempt to download Windows_x64.zip, complete at 100%. It'd than extract the zip. Once extracted hits 100% the app closes and the CMD pops up. Any time I open Slithin it does this all over again.
**To Reproduce**
1. Open Slithin
2. ???
3. Proift

**Expected behavior**
to allow the app when it reopens to let me interact with Slithin's features. 

**Screenshots**
Recording: https://screencast-o-matic.com/watch/crQq1rV6ok3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10

**Comment by furesoft** [comment]
Do you use the Windows Store Version or the version from the release page?

**Comment by iball** [comment]
I'm seeing the same thing.  Windows Store version.

**Comment by furesoft** [comment]
Due some problems with the policies of the publish of updates I can't upload a fixed version to the store

I already mentioned the problem with the file select screen. It seems to be a problem from avalonia or my configuration of the application

**Comment by furesoft** [comment]
I have published a new version to the store. does it works now?
