### ISSUE TITLE
[Bug] unable to build on Linux

### ISSUE THREAD

**Issue by ibespo** [furesoft/Slithin#315]
Chris,

[moving this from the pre-existing deb install thread, after suggestion I try building my own to test w/current SSL library]
Have removed all traces of dotnet6, and upgraded to dotnet7 as per the other thread. (just to confirm, I also have libgdiplus installed).

Good news is that there's no errors related to SSL, however... build starts pauses for a couple of seconds, and then fails with the attached output. 

Running Linux Mint 21.1. 

Appreciate any recommendations. 

<details>
<summary>error here</summary>

> /home/ibespo/Slithin/Source/Slithin/Core/Sync/IRepository.cs(5,22): error CS0246: The type or namespace name 'Template' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/AddTemplateValidator.cs(5,55): error CS0246: The type or namespace name 'AddTemplateModalViewModel' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/IRepository.cs(7,5): error CS0246: The type or namespace name 'Template' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/IRepository.cs(9,25): error CS0246: The type or namespace name 'Template' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/AddTemplateValidator.cs(21,67): error CS0246: The type or namespace name 'AddTemplateModalViewModel' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/AddTemplateValidator.cs(7,22): error CS0246: The type or namespace name 'ILocalisationService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/AddTemplateValidator.cs(9,33): error CS0246: The type or namespace name 'ILocalisationService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/DeviceRepository.cs(24,21): error CS0246: The type or namespace name 'CustomScreen' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/AppendNotebookValidator.cs(5,58): error CS0246: The type or namespace name 'AppendNotebookModalViewModel' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/DeviceRepository.cs(32,29): error CS0246: The type or namespace name 'Template' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/AppendNotebookValidator.cs(7,36): error CS0246: The type or namespace name 'ILocalisationService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/DeviceRepository.cs(79,12): error CS0246: The type or namespace name 'Template' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/CreateNotebookValidator.cs(5,58): error CS0246: The type or namespace name 'CreateNotebookModalViewModel' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/DeviceRepository.cs(108,24): error CS0246: The type or namespace name 'Metadata' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/CreateNotebookValidator.cs(7,36): error CS0246: The type or namespace name 'ILocalisationService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/DeviceRepository.cs(122,32): error CS0246: The type or namespace name 'Template' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/ExportValidator.cs(6,50): error CS0246: The type or namespace name 'ExportModalViewModel' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/DeviceRepository.cs(10,22): error CS0246: The type or namespace name 'ILoadingService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/LocalRepository.cs(29,29): error CS0246: The type or namespace name 'Template' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/ExportValidator.cs(22,70): error CS0246: The type or namespace name 'ExportModalViewModel' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/DeviceRepository.cs(12,22): error CS0246: The type or namespace name 'IPathManager' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/LocalRepository.cs(52,12): error CS0246: The type or namespace name 'Template' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/ExportValidator.cs(8,22): error CS0246: The type or namespace name 'ILocalisationService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/ExportValidator.cs(10,28): error CS0246: The type or namespace name 'ILocalisationService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/LocalRepository.cs(70,24): error CS0246: The type or namespace name 'Metadata' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/DeviceRepository.cs(15,9): error CS0246: The type or namespace name 'IPathManager' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/DeviceRepository.cs(17,9): error CS0246: The type or namespace name 'ILoadingService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/LocalRepository.cs(87,32): error CS0246: The type or namespace name 'Template' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/LoginInfoValidator.cs(5,53): error CS0246: The type or namespace name 'LoginInfo' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/LocalRepository.cs(9,22): error CS0246: The type or namespace name 'IPathManager' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/LoginInfoValidator.cs(19,71): error CS0246: The type or namespace name 'LoginInfo' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/LoginInfoValidator.cs(7,22): error CS0246: The type or namespace name 'ILocalisationService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/LocalRepository.cs(10,22): error CS0246: The type or namespace name 'IVersionService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Validators/LoginInfoValidator.cs(9,31): error CS0246: The type or namespace name 'ILocalisationService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/LocalRepository.cs(12,28): error CS0246: The type or namespace name 'IPathManager' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> /home/ibespo/Slithin/Source/Slithin/Core/Sync/Repositorys/LocalRepository.cs(12,54): error CS0246: The type or namespace name 'IVersionService' could not be found (are you missing a using directive or an assembly reference?) [/home/ibespo/Slithin/Source/Slithin/Slithin.csproj]
> 
> The build failed. Fix the build errors and run again.

</details>

**Comment by furesoft** [comment]
the Slithin/Source/Slithin project is the old code I did not remove yet. To build the current project you have to use the /Slithin/Source/New/Slithin project. Then it should work. The old source files will be removed if the rewrite is complete.

**Comment by ibespo** [comment]
Well, I certainly see how that would make a difference! But... still not happy for me I'm afraid.

<details>
<summary>error here</summary>
/home/ibespo/Slithin/Source/New/Models/Slithin.Modules.Settings.Models/SettingsModel.cs(36,16): warning CS8603: Possible null reference return. [/home/ibespo/Slithin/Source/New/Models/Slithin.Modules.Settings.Models/Slithin.Modules.Settings.Models.csproj]
/home/ibespo/Slithin/Source/New/Models/Slithin.Modules.Settings.Models/SettingsModel.cs(12,19): warning CS8618: Non-nullable property 'MarketplaceToken' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/home/ibespo/Slithin/Source/New/Models/Slithin.Modules.Settings.Models/Slithin.Modules.Settings.Models.csproj]
/home/ibespo/Slithin/Source/Slithin.Modules.UI/DialogHost.cs(9,34): warning CS8618: Non-nullable field '_host' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/ibespo/Slithin/Source/Slithin.Modules.UI/Slithin.Modules.UI.Models.csproj]
/home/ibespo/Slithin/Source/New/Models/Slithin.Modules.Sync.Models/SyncNotebook.cs(9,21): warning CS8618: Non-nullable property 'Metadata' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/home/ibespo/Slithin/Source/New/Models/Slithin.Modules.Sync.Models/Slithin.Modules.Sync.Models.csproj]
/home/ibespo/Slithin/Source/New/Models/Slithin.Modules.Sync.Models/NotebooksFilter.cs(18,27): warning CS8618: Non-nullable property 'ParentFolder' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/home/ibespo/Slithin/Source/New/Models/Slithin.Modules.Sync.Models/Slithin.Modules.Sync.Models.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/XochitlImpl.cs(16,12): warning CS8618: Non-nullable field '_data' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/Slithin.Modules.Device.Mock.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/MockDevice.cs(15,12): warning CS8618: Non-nullable field '_filesystem' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/Slithin.Modules.Device.Mock.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/MockDevice.cs(15,12): warning CS8618: Non-nullable event 'Downloading' must contain a non-null value when exiting constructor. Consider declaring the event as nullable. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/Slithin.Modules.Device.Mock.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/MockDevice.cs(15,12): warning CS8618: Non-nullable event 'Uploading' must contain a non-null value when exiting constructor. Consider declaring the event as nullable. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/Slithin.Modules.Device.Mock.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/Module.cs(18,9): warning CS8602: Dereference of a possibly null reference. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/Slithin.Modules.Device.Mock.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/MockDevice.cs(27,51): warning CS0067: The event 'MockDevice.Uploading' is never used [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/Slithin.Modules.Device.Mock.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/MockDevice.cs(25,53): warning CS0067: The event 'MockDevice.Downloading' is never used [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Device.Mock/Slithin.Modules.Device.Mock.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/ThumbnailLoaderImpl.cs(14,20): warning CS8766: Nullability of reference types in return type of 'IImage? ThumbnailLoaderImpl.LoadImage(FileSystemModel model)' doesn't match implicitly implemented member 'IImage IThumbnailLoader.LoadImage(FileSystemModel model)' (possibly because of nullability attributes). [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/DatabaseServiceImpl.cs(13,12): warning CS8618: Non-nullable field '_db' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/LocalRepository.cs(66,16): warning CS8603: Possible null reference return. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/VersionServiceImpl.cs(48,16): warning CS8603: Possible null reference return. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/LoginServiceImpl.cs(15,12): warning CS8618: Non-nullable field '_pathManager' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/LoginServiceImpl.cs(15,12): warning CS8618: Non-nullable field '_dbService' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/LoginServiceImpl.cs(28,16): warning CS8603: Possible null reference return. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/LoginServiceImpl.cs(58,30): warning CS8604: Possible null reference argument for parameter 'obj' in 'void DatabaseAccessor.Update<LoginInfo>(LoginInfo obj)'. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/LoginServiceImpl.cs(72,30): warning CS8604: Possible null reference argument for parameter 'id' in 'void DatabaseAccessor.Delete<LoginInfo>(ObjectId id)'. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/LoadingServiceImpl.cs(78,9): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/LoadingServiceImpl.cs(82,13): warning CS4014: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/ThumbnailLoaderImpl.cs(28,34): warning CS8602: Dereference of a possibly null reference. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/ThumbnailLoaderImpl.cs(52,34): warning CS8602: Dereference of a possibly null reference. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/TemplateStorageImpl.cs(45,23): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/TemplateStorageImpl.cs(12,51): warning CS8618: Non-nullable property 'Templates' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/home/ibespo/Slithin/Source/New/Modules/Slithin.Modules.Repository/Slithin.Modules.Repository.csproj]
/home/ibespo/Slithin/Source/New/Models/Slithin.Modules.Export.Models/ExportOptions.cs(5,27): warning CS8618: Non-nullable property 'Document' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/home/ibespo/Slithin/Source/New/Models/Slithin.Modules.Export.Models/Slithin.Modules.Export.Models.csproj]
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at AuroraModularis.Core.ServiceContainer.FactoryFromType(Type itemType)
   at AuroraModularis.Core.ServiceContainer.GetService(Type type)
   at AuroraModularis.Core.ServiceContainerExtensions.Resolve[T](IScope scope)
   at Slithin.Core.LocalisationExtension.ProvideValue(IServiceProvider serviceProvider) in /home/ibespo/Slithin/Source/New/Slithin.Core/LocalisationExtension.cs:line 17
   at Slithin.Views.ConnectWindow.!XamlIlPopulate(IServiceProvider, ConnectWindow) in /home/ibespo/Slithin/Source/New/Slithin/Views/ConnectWindow.axaml:line 18
   at Slithin.Views.ConnectWindow.!XamlIlPopulateTrampoline(ConnectWindow)
   at Slithin.Views.ConnectWindow.InitializeComponent() in /home/ibespo/Slithin/Source/New/Slithin/Views/ConnectWindow.axaml.cs:line 22
   at Slithin.Views.ConnectWindow..ctor() in /home/ibespo/Slithin/Source/New/Slithin/Views/ConnectWindow.axaml.cs:line 13
   at Slithin.App.OnFrameworkInitializationCompleted() in /home/ibespo/Slithin/Source/New/Slithin/App.axaml.cs:line 32
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 181
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Threading.Dispatcher.RunJobs() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 73
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 199
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at Slithin.Program.Main() in /home/ibespo/Slithin/Source/New/Slithin/Program.cs:line 16
</details>
