### ISSUE TITLE
[Bug] Link to instructions broken

### ISSUE THREAD

**Issue by karliwalti** [furesoft/Slithin#336]
**Describe the bug**
The link to the instructions on first page is broken: https://remarkablewiki.com/tech/ssh is down?

**To Reproduce**
1. Start program
2. Click on 'Where can I find this information?'

**Expected behavior**
Agood manual how to use this software

**Desktop (please complete the following information):**
 - Windows 10

**Additional context** 
I think it is a generic problem with remakablewiki.com or it no longer exist

**Comment by furesoft** [comment]
Thanks for your hint, it will be integrated directly in the application
