### ISSUE TITLE
[Bug] Crash on connection

### ISSUE THREAD

**Issue by Ombrelin** [furesoft/Slithin#48]
**Describe the bug**
The app exits when I click connect, but if I connect using SSH CLI or SFTP (filezilla) it works

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by orsinium** [comment]
What was the issue? Is it fixed? I have the same issue on Windows 10. What's interesting, in some compatibility modes, it opens the next window for a fraction of a second but then still dies without any messages. Does it write any logs? If so, how can I find them? I can dig out the error and open a new issue. Thank you.

**Comment by Ombrelin** [comment]
Hello, I'm writing back to you because I've a similar problem again.
Here is the log file from the top level file :
[log.txt](https://github.com/furesoft/Slithin/files/8566701/log.txt)
 And the logs from the device directory : 
[log.txt](https://github.com/furesoft/Slithin/files/8566703/log.txt)

Thank you in advance,
