### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by mioxoim** [furesoft/Slithin#55]
I've tried a number of ways to install this on Linux and i cannot seem to figure it out.

I would love an install guide and I am sure future users would appreciate one too!

Thank you for this piece of software!

**Comment by furesoft** [comment]
I will cover this. Thanks for your issue. Which distro do you use?

**Comment by mioxoim** [comment]
pop_os/ubuntu
    On Thursday, December 2, 2021, 12:44:20 p.m. EST, Chris ***@***.***> wrote:  
 
 


I will cover this. Thanks for your issue. Which distro do you use?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by furesoft** [comment]
you can install through the terminal:

sudo dpkg -i pathOfDebFile

**Comment by furesoft** [comment]
Does it work?

**Comment by mioxoim** [comment]
Since I couldnt find a .deb file, so I tried to compile it using mono-complete in Slithin/Source/Slithin:

mcs -Program.exe Program.cs

**Comment by furesoft** [comment]
A deb file is under releases: https://github.com/furesoft/Slithin/releases
If you want to compile you have to use dotnet 6

**Comment by mioxoim** [comment]
I tried to install that way, this was the result:
note: I have libicu-dev installed
 sudo dpkg -i Downloads/Slithin.1.0.3.0.linux-x64.deb
Selecting previously unselected package slithin.
(Reading database ... 310107 files and directories currently installed.)
Preparing to unpack .../Slithin.1.0.3.0.linux-x64.deb ...
Unpacking slithin (1.0.3.0) ...
dpkg: dependency problems prevent configuration of slithin:
 slithin depends on libicu66 | libicu65 | libicu64 | libicu63 | libicu62 | libicu61 | libicu60 | libicu59 | libicu58 | libicu57 | libicu56 | libicu55 | libicu54 | libicu53 | libicu52; however:
  Package libicu66 is not installed.
  Package libicu65 is not installed.
  Package libicu64 is not installed.
  Package libicu63 is not installed.
  Package libicu62 is not installed.
  Package libicu61 is not installed.
  Package libicu60 is not installed.
  Package libicu59 is not installed.
  Package libicu58 is not installed.
  Package libicu57 is not installed.
  Package libicu56 is not installed.
  Package libicu55 is not installed.
  Package libicu54 is not installed.
  Package libicu53 is not installed.
  Package libicu52 is not installed.

dpkg: error processing package slithin (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu1) ...
Processing triggers for mailcap (3.68ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 slithin

**Comment by furesoft** [comment]
Try To use this command and try to install the deb again:
`
sudo apt install --fix-broken
`

**Comment by mioxoim** [comment]
This is my result:
I dont know why my /usr/local/bin would need to be empty.

`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  libboost-program-options1.74.0 libboost-regex1.74.0 linux-headers-5.13.0-7614 linux-headers-5.13.0-7614-generic
  linux-image-5.11.0-40-generic linux-image-5.13.0-7614-generic linux-modules-5.11.0-40-generic linux-modules-5.13.0-7614-generic
  linux-modules-extra-5.13.0-7614-generic
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  slithin
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 135 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 310439 files and directories currently installed.)
Removing slithin (1.0.3.0) ...
dpkg: warning: while removing slithin, directory '/usr/local/bin' not empty so not removed
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mailcap (3.68ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu1) ...`

**Comment by furesoft** [comment]
Is Slithin on your AppList now?

**Comment by mioxoim** [comment]
yes, i tried to make it executalbe when i was guessing to install.

**Comment by furesoft** [comment]
Then it should work now
