### ISSUE TITLE
[Bug] "An error occured, see log file" on startup

### ISSUE THREAD

**Issue by Ombrelin** [furesoft/Slithin#79]
**Describe the bug**
When logging to device, the main screen appears, but sync throws an error : 

**Screenshots**
![image](https://user-images.githubusercontent.com/47502331/152644234-9efe892e-3789-4dbf-bb90-30b5741aa811.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
- Intalled from the windows store

**Additional context** 
Please find attached the "log.txt" file from the "Slithin" folder in Documents : [log.txt](https://github.com/furesoft/Slithin/files/8008103/log.txt)

And indeed, as the log states, there is no ".version" file in the Slithin folder : 

![image](https://user-images.githubusercontent.com/47502331/152644322-aa9fcc59-128c-4d55-913b-b84fca37b9e2.png)

**Comment by furesoft** [comment]
I will look at it

Arsène Lapostolet ***@***.***> schrieb am Sa., 5. Feb. 2022,
14:34:

**Comment by furesoft** [comment]
Problem is fixed. But I don't have Internet right now to publish Updates. It may take a while
